CREATE TABLE ENROLL(
  Snn      INT(9)		  NOT NULL		DEFAULT 999999999,
  Course#  INT	      NOT NULL		DEFAULT 0,
  Semester INT		    DEFAULT 0,
  Year		 INT(4)		  CHECK(Year >= 2000),
  Grade		 VARYING(3)	DEFAULT 0,
  CONSTRAINT SSNFK
    FOREIGN KEY(ENROLL.Snn) REFERENCES STUDENT(STUDENT.Snn)
      ON DELETE SET DEFAULT	ON UPDATE CASCADE,
  CONSTRAINT COURSEFK
    FOREIGN KEY(ENROLL.Course#) REFERENCES COURSE(COURSE.Course#)
      ON DELETE SET DEFAULT	ON UPDATE CASCADE,
);

----------

CREATE TABLE IF NOT EXISTS Questions(
  id INTEGER GENERATED ALWAYS AS IDENTITY,
  question VARCHAR(500) UNIQUE NOT NULL,
  difficulty SMALLINT NOT NULL,
  option1 VARCHAR(50) NOT NULL,
  option2 VARCHAR(50) NOT NULL,
  option3 VARCHAR(50) DEFAULT NULL,
  option4 VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
);
